dist: trusty
language: java
jdk:
  - openjdk8

sudo: false

cache:
  directories:
    - "$HOME/.m2"

script: "mvn clean verify"

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN=16448894-f54c-448b-9455-0641748301e5