language: java

sudo: required

services:
  - docker

cache:
  directories:
    - "$HOME/.m2"

before_install:
  - docker pull cassandra:3.11.2
  - docker pull scylladb/scylla

script: "mvn clean verify"

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN=16448894-f54c-448b-9455-0641748301e5