language: java

sudo: required

jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
    - "$HOME/.m2"

before_install:
  - docker pull cassandra:latest
  - docker pull scylladb/scylla

script: "mvn clean verify"

after_success:
  - bash <(curl -s https://codecov.io/bash)
