DROP KEYSPACE IF EXISTS test_keyspace;
DROP TYPE IF EXISTS test_keyspace.test_udt;
DROP TYPE IF EXISTS test_keyspace.test_extra_udt;
DROP TYPE IF EXISTS test_keyspace.test_nested_udt;
DROP TABLE IF EXISTS test_keyspace.test_entity;
DROP TABLE IF EXISTS test_keyspace.test_entity_by_date;
DROP INDEX IF EXISTS test_keyspace.test_entity_flag_idx;
DROP INDEX IF EXISTS test_keyspace.test_entity_by_date_flag_idx;
